name: sqflite_hooks
description: A new flutter plugin project.
version: 1.0.0
author: Tom Alabaster
homepage: https://github.com/tomalabaster/sqflite_hooks

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  sqflite: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
