name: sqflite_hooks
description: An extension to sqflite for adding hooks to database actions.
version: 1.4.0
author: Tom Alabaster <tomalabasteruk@gmail.com>
homepage: https://github.com/tomalabaster/sqflite_hooks

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  sqflite: ^1.1.7+2
  flutter:
    sdk: flutter

dev_dependencies:
  mockito:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
